<?php if (1 == $block->isProductWithPlan()):
    $nuvei_texts    = $block->getTexts(); ?>

    <div id="nuvei_plan_details" style="display: none;">
        <h4><?= $block->escapeHtml($nuvei_texts['table_title']); ?></h4>
        <table border="1">
            <tr>
                <td><?= $block->escapeHtml($nuvei_texts['rec_length']); ?></td>
                <td id="nuvei_rec_length">&nbsp;</td>
            </tr>
            <tr>
                <td><?= $block->escapeHtml($nuvei_texts['rec_period']); ?></td>
                <td id="nuvei_rec_period">&nbsp;</td>
            </tr>
            <tr>
                <td><?= $block->escapeHtml($nuvei_texts['rec_amount']); ?></td>
                <td id="nuvei_rec_amount">&nbsp;</td>
            </tr>
            <tr>
                <td><?= $block->escapeHtml($nuvei_texts['trial_period']); ?></td>
                <td id="nuvei_trial_period">&nbsp;</td>
            </tr>
        </table>
    </div>
    
    <script>
        require([
            'jquery'
        ], function($){
            var prodOptions = {};
            
            $(function() {
                $('select.super-attribute-select').on('change', function() {
                    var _self       = $(this);
                    var attrId      = _self.attr('id').replace('attribute', '');
                    var attrVal     = _self.val();
                    var doAjaxCall  = true;
                    
                    prodOptions[attrId] = attrVal;
                    
                    // when select an empty option - hide the info table
                    if('' == attrVal) {
                        $('#nuvei_plan_details').css('display', 'none');
                        return;
                    }
                    
                    // check if all available options are selected
                    $('#product-options-wrapper select.super-attribute-select').each(function() {
                        var _currSelect = $(this);
                        
//                        console.log($('option:selected', _currSelect).val())
                        
                        if(_currSelect.val() == ''
                            || ( typeof _currSelect.attr('disabled') != 'undefined' 
                                && _currSelect.attr('disabled') == true )
                        ) {
                            doAjaxCall = false;
                            return;
                        }
                    });
                    
                    // if there is missing option stop the process
                    if(!doAjaxCall) {
                        return;
                    }
                    
                    // do an ajax call to get the data for the selected product variation
                    $.ajax({
                        dataType: "json",
                        type: 'post',
                        url: '<?= $block->escapeUrl($nuvei_texts['nuvei_ajax_url']); ?>',
                        data: {
                            prodId      : '<?= /* @noEscape */ $nuvei_texts['nuvei_prod_id']; ?>',
                            prodOptions : prodOptions
                        },
                        cache: false,
                        showLoader: true
                    })
                        .done(function(resp){
                            console.log(resp);
                            
                            
                            if(typeof resp != 'undefined' && '' != resp) {
                                var respObj = JSON.parse(resp);
                                
                                if(respObj.hasOwnProperty('rec_len')) {
                                    $('#nuvei_rec_length').html(respObj.rec_len);
                                }
                                if(respObj.hasOwnProperty('rec_period')) {
                                    $('#nuvei_rec_period').html(respObj.rec_period);
                                }
                                if(respObj.hasOwnProperty('rec_amount')) {
                                    $('#nuvei_rec_amount').html(respObj.rec_amount);
                                }
                                if(respObj.hasOwnProperty('trial_period')) {
                                    $('#nuvei_trial_period').html(respObj.trial_period);
                                }
                                
                                $('#nuvei_plan_details').css('display', 'block');
                            }
                        });
                });
            });
        });
    </script>
<?php endif; ?>