<?php
/**
 * @var Magento\Payment\Block\Adminhtml\Transparent\Form $block
 */
?>
<?php
$code = $block->escapeHtml($block->getMethodCode());

$ccType = $block->getInfoData('cc_type');
$ccExpMonth = $block->getInfoData('cc_exp_month');
$ccExpYear = $block->getInfoData('cc_exp_year');
?>

<fieldset class="admin__fieldset payment-method"
          id="payment_form_<?php /* @noEscape */ echo $code; ?>"
          style="display:none;">

    <div class="admin__field _required">
        <label for="<?php /* @noEscape */ echo $code; ?>_cc_type"
               class="admin__field-label">
            <span><?php echo $block->escapeHtml(__('Credit Card Type')); ?></span>
        </label>
        <div class="admin__field-control">
            <select id="<?php /* @noEscape */ echo $code; ?>_cc_type"
                    name="payment[cc_type]"
                    class="required-entry validate-cc-type-select
                    admin__control-select">
                <option value=""></option>
                <?php $availableTypes = $block->getCcAvailableTypes() ?>
                <?php foreach ($availableTypes as $typeCode => $typeName) : ?>
                    <?php
                    $selected = $typeCode === $ccType
                        ? 'selected="selected"'
                        : '';
                    ?>
                    <option value="<?php echo $block->escapeHtml($typeCode); ?>"
                            <?php echo $selected ?>>
                        <?php echo $block->escapeHtml($typeName); ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>

    <div class="admin__field _required">
        <label for="<?php /* @noEscape */ echo $code; ?>_cc_number"
               class="admin__field-label">
            <span><?php echo $block->escapeHtml(__('Card Number')); ?></span>
        </label>

        <div class="admin__field-control">
            <input type="tel" id="<?php /* @noEscape */ echo $code; ?>_cc_number"
                   name="payment[cc_number]"
                   class="input-text required-entry validate-cc-number admin__control-text"
                   maxlength="19"
                   value="<?php /* @noEscape */ echo $block->getInfoData('cc_number'); ?>"/>
        </div>
    </div>

    <div class="admin__field _required">
        <label for="<?php /* @noEscape */ echo $code; ?>_expiration"
               class="admin__field-label">
            <span><?php echo $block->escapeHtml(__('Expiration Date')); ?></span>
        </label>

        <div class="admin__field-control">
            <select id="<?php /* @noEscape */ echo $code; ?>_expiration"
                    name="payment[cc_exp_month]"
                    class="validate-cc-exp required-entry admin__control-select
                    admin__control-select-month">
                <?php foreach ($block->getCcMonths() as $k => $v) : ?>
                    <?php
                    $selected = $k === $ccExpMonth
                        ? 'selected="selected"'
                        : '';
                    ?>
                    <option value="<?php echo $block->escapeHtml($k); ?>"
                            <?php echo $selected ?>>
                        <?php echo $block->escapeHtml($v); ?>
                    </option>
                <?php endforeach; ?>
            </select>
            <select id="<?php /* @noEscape */ echo $code; ?>_expiration_yr"
                    name="payment[cc_exp_year]"
                    class="required-entry admin__control-select
                    admin__control-select-year">
                <?php foreach ($block->getCcYears() as $k => $v) : ?>
                    <?php
                    $selected = $k === $ccExpYear
                        ? 'selected="selected"'
                        : '';
                    $value = $k ? $block->escapeHtml($k) : '';
                    ?>
                    <option value="<?php /* @noEscape */ echo $value; ?>"
                            <?php echo $selected ?>>
                        <?php echo $block->escapeHtml($v); ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>

    <div class="admin__field _required">
        <label for="<?php /* @noEscape */ echo $code; ?>_cc_owner"
               class="admin__field-label">
            <span><?php echo $block->escapeHtml(__('Name On Card')); ?></span>
        </label>

        <div class="admin__field-control">
            <input type="text" id="<?php /* @noEscape */ echo $code; ?>_cc_owner"
                   name="payment[cc_owner]"
                   class="input-text required-entry admin__control-text"
                   value="<?php /* @noEscape */ echo $block->getInfoData('cc_owner'); ?>"/>
        </div>
    </div>

    <?php if ($block->hasVerification()) : ?>
        <div class="admin__field _required">
            <label for="<?php /* @noEscape */ echo $code; ?>_cc_cid"
                   class="admin__field-label">
                <span><?php echo $block->escapeHtml(__('Card Verification Number')); ?></span>
            </label>

            <div class="admin__field-control">
                <input type="tel"
                       class="required-entry input-text validate-cc-cvn admin__control-text"
                       maxlength="4"
                       id="<?php /* @noEscape */ echo $code; ?>_cc_cid"
                       name="payment[cc_cid]"
                       value="<?php /* @noEscape */ echo $block->getInfoData('cc_cid') ?>"/>
            </div>
        </div>
    <?php endif; ?>
</fieldset>