<script>
    require([
        'jquery',
        'prototype'
    ], function(jQuery){
        jQuery('#get_plans_button').click(function () {
            jQuery('#plans_message').text('');
            jQuery('#loading_span .loaded').hide();
            
            jQuery.ajax({
                url: '<?= $block->escapeUrl($block->getAjaxUrl()); ?>',
                showLoader: true,
                data: {
                    form_key:'<?= /* @noEscape */ $block->getFormKey(); ?>'
                },
                type: "POST",
                
                complete: function(xhr, textStatus) {
                    var resultText = '';
                    
                    if (xhr.status > 200) {
                        resultText = textStatus;
                    } else {
                        resultText = ('success' == textStatus) ? 'Success' : 'Error';
                        jQuery('#loading_span .loaded').show();
                    }

                    jQuery('#plans_message').text(resultText);
                } 
            });
        });
    });
</script>

<?= $block->getButtonHtml(); ?>&nbsp;

<span class="collect-indicator" id="loading_span">
    <img class="loaded" 
         hidden="hidden" 
         alt="loaded" 
         style="margin:-3px 5px" 
         src="<?= $block->escapeUrl($block->getViewFileUrl('images/rule_component_apply.gif')); ?>"/>
    
    <span id="plans_message"></span>
</span>
